// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BINDINGPOINT_TENSOR_SIMULATION_H_
#define FLATBUFFERS_GENERATED_BINDINGPOINT_TENSOR_SIMULATION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace tensor {
namespace simulation {

struct ip_int;
struct ip_intBuilder;

struct ip_bytes;

struct binding_point;
struct binding_pointBuilder;

enum address : uint8_t {
  address_NONE = 0,
  address_ip_int = 1,
  address_ip_bytes = 2,
  address_MIN = address_NONE,
  address_MAX = address_ip_bytes
};

inline const address (&EnumValuesaddress())[3] {
  static const address values[] = {
    address_NONE,
    address_ip_int,
    address_ip_bytes
  };
  return values;
}

inline const char * const *EnumNamesaddress() {
  static const char * const names[4] = {
    "NONE",
    "ip_int",
    "ip_bytes",
    nullptr
  };
  return names;
}

inline const char *EnumNameaddress(address e) {
  if (::flatbuffers::IsOutRange(e, address_NONE, address_ip_bytes)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesaddress()[index];
}

template<typename T> struct addressTraits {
  static const address enum_value = address_NONE;
};

template<> struct addressTraits<tensor::simulation::ip_int> {
  static const address enum_value = address_ip_int;
};

template<> struct addressTraits<tensor::simulation::ip_bytes> {
  static const address enum_value = address_ip_bytes;
};

bool Verifyaddress(::flatbuffers::Verifier &verifier, const void *obj, address type);
bool VerifyaddressVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) ip_bytes FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t bytes_[4];

 public:
  ip_bytes()
      : bytes_() {
  }
  ip_bytes(::flatbuffers::span<const uint8_t, 4> _bytes) {
    ::flatbuffers::CastToArray(bytes_).CopyFromSpan(_bytes);
  }
  const ::flatbuffers::Array<uint8_t, 4> *bytes() const {
    return &::flatbuffers::CastToArray(bytes_);
  }
};
FLATBUFFERS_STRUCT_END(ip_bytes, 4);

struct ip_int FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ip_intBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IP = 4
  };
  uint32_t ip() const {
    return GetField<uint32_t>(VT_IP, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_IP, 4) &&
           verifier.EndTable();
  }
};

struct ip_intBuilder {
  typedef ip_int Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ip(uint32_t ip) {
    fbb_.AddElement<uint32_t>(ip_int::VT_IP, ip, 0);
  }
  explicit ip_intBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ip_int> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ip_int>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ip_int> Createip_int(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ip = 0) {
  ip_intBuilder builder_(_fbb);
  builder_.add_ip(ip);
  return builder_.Finish();
}

struct binding_point FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef binding_pointBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PORT = 4,
    VT_IP_TYPE = 6,
    VT_IP = 8
  };
  int16_t port() const {
    return GetField<int16_t>(VT_PORT, 0);
  }
  tensor::simulation::address ip_type() const {
    return static_cast<tensor::simulation::address>(GetField<uint8_t>(VT_IP_TYPE, 0));
  }
  const void *ip() const {
    return GetPointer<const void *>(VT_IP);
  }
  template<typename T> const T *ip_as() const;
  const tensor::simulation::ip_int *ip_as_ip_int() const {
    return ip_type() == tensor::simulation::address_ip_int ? static_cast<const tensor::simulation::ip_int *>(ip()) : nullptr;
  }
  const tensor::simulation::ip_bytes *ip_as_ip_bytes() const {
    return ip_type() == tensor::simulation::address_ip_bytes ? static_cast<const tensor::simulation::ip_bytes *>(ip()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_PORT, 2) &&
           VerifyField<uint8_t>(verifier, VT_IP_TYPE, 1) &&
           VerifyOffset(verifier, VT_IP) &&
           Verifyaddress(verifier, ip(), ip_type()) &&
           verifier.EndTable();
  }
};

template<> inline const tensor::simulation::ip_int *binding_point::ip_as<tensor::simulation::ip_int>() const {
  return ip_as_ip_int();
}

template<> inline const tensor::simulation::ip_bytes *binding_point::ip_as<tensor::simulation::ip_bytes>() const {
  return ip_as_ip_bytes();
}

struct binding_pointBuilder {
  typedef binding_point Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_port(int16_t port) {
    fbb_.AddElement<int16_t>(binding_point::VT_PORT, port, 0);
  }
  void add_ip_type(tensor::simulation::address ip_type) {
    fbb_.AddElement<uint8_t>(binding_point::VT_IP_TYPE, static_cast<uint8_t>(ip_type), 0);
  }
  void add_ip(::flatbuffers::Offset<void> ip) {
    fbb_.AddOffset(binding_point::VT_IP, ip);
  }
  explicit binding_pointBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<binding_point> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<binding_point>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<binding_point> Createbinding_point(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t port = 0,
    tensor::simulation::address ip_type = tensor::simulation::address_NONE,
    ::flatbuffers::Offset<void> ip = 0) {
  binding_pointBuilder builder_(_fbb);
  builder_.add_ip(ip);
  builder_.add_port(port);
  builder_.add_ip_type(ip_type);
  return builder_.Finish();
}

inline bool Verifyaddress(::flatbuffers::Verifier &verifier, const void *obj, address type) {
  switch (type) {
    case address_NONE: {
      return true;
    }
    case address_ip_int: {
      auto ptr = reinterpret_cast<const tensor::simulation::ip_int *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case address_ip_bytes: {
      return verifier.VerifyField<tensor::simulation::ip_bytes>(static_cast<const uint8_t *>(obj), 0, 1);
    }
    default: return true;
  }
}

inline bool VerifyaddressVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!Verifyaddress(
        verifier,  values->Get(i), types->GetEnum<address>(i))) {
      return false;
    }
  }
  return true;
}

inline const tensor::simulation::binding_point *Getbinding_point(const void *buf) {
  return ::flatbuffers::GetRoot<tensor::simulation::binding_point>(buf);
}

inline const tensor::simulation::binding_point *GetSizePrefixedbinding_point(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<tensor::simulation::binding_point>(buf);
}

inline bool Verifybinding_pointBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<tensor::simulation::binding_point>(nullptr);
}

inline bool VerifySizePrefixedbinding_pointBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<tensor::simulation::binding_point>(nullptr);
}

inline void Finishbinding_pointBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<tensor::simulation::binding_point> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedbinding_pointBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<tensor::simulation::binding_point> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace simulation
}  // namespace tensor

#endif  // FLATBUFFERS_GENERATED_BINDINGPOINT_TENSOR_SIMULATION_H_
