// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_NETWORKSPEC_TENSOR_NETWORK_CONFIG_H_
#define FLATBUFFERS_GENERATED_NETWORKSPEC_TENSOR_NETWORK_CONFIG_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace tensor {
namespace network {
namespace config {

struct edge;
struct edgeBuilder;

struct graph;
struct graphBuilder;

struct network;
struct networkBuilder;

enum network_type : int16_t {
  network_type_link_based = 0,
  network_type_MIN = network_type_link_based,
  network_type_MAX = network_type_link_based
};

inline const network_type (&EnumValuesnetwork_type())[1] {
  static const network_type values[] = {
    network_type_link_based
  };
  return values;
}

inline const char * const *EnumNamesnetwork_type() {
  static const char * const names[2] = {
    "link_based",
    nullptr
  };
  return names;
}

inline const char *EnumNamenetwork_type(network_type e) {
  if (::flatbuffers::IsOutRange(e, network_type_link_based, network_type_link_based)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesnetwork_type()[index];
}

struct edge FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef edgeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FROM = 4,
    VT_TO = 6,
    VT_WEIGHT = 8
  };
  uint64_t from() const {
    return GetField<uint64_t>(VT_FROM, 0);
  }
  uint64_t to() const {
    return GetField<uint64_t>(VT_TO, 0);
  }
  double weight() const {
    return GetField<double>(VT_WEIGHT, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_FROM, 8) &&
           VerifyField<uint64_t>(verifier, VT_TO, 8) &&
           VerifyField<double>(verifier, VT_WEIGHT, 8) &&
           verifier.EndTable();
  }
};

struct edgeBuilder {
  typedef edge Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_from(uint64_t from) {
    fbb_.AddElement<uint64_t>(edge::VT_FROM, from, 0);
  }
  void add_to(uint64_t to) {
    fbb_.AddElement<uint64_t>(edge::VT_TO, to, 0);
  }
  void add_weight(double weight) {
    fbb_.AddElement<double>(edge::VT_WEIGHT, weight, 0.0);
  }
  explicit edgeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<edge> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<edge>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<edge> Createedge(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t from = 0,
    uint64_t to = 0,
    double weight = 0.0) {
  edgeBuilder builder_(_fbb);
  builder_.add_weight(weight);
  builder_.add_to(to);
  builder_.add_from(from);
  return builder_.Finish();
}

struct graph FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef graphBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NODES = 4,
    VT_EDGES = 6
  };
  const ::flatbuffers::Vector<uint64_t> *nodes() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_NODES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<tensor::network::config::edge>> *edges() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<tensor::network::config::edge>> *>(VT_EDGES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NODES) &&
           verifier.VerifyVector(nodes()) &&
           VerifyOffset(verifier, VT_EDGES) &&
           verifier.VerifyVector(edges()) &&
           verifier.VerifyVectorOfTables(edges()) &&
           verifier.EndTable();
  }
};

struct graphBuilder {
  typedef graph Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_nodes(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> nodes) {
    fbb_.AddOffset(graph::VT_NODES, nodes);
  }
  void add_edges(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<tensor::network::config::edge>>> edges) {
    fbb_.AddOffset(graph::VT_EDGES, edges);
  }
  explicit graphBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<graph> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<graph>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<graph> Creategraph(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> nodes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<tensor::network::config::edge>>> edges = 0) {
  graphBuilder builder_(_fbb);
  builder_.add_edges(edges);
  builder_.add_nodes(nodes);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<graph> CreategraphDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint64_t> *nodes = nullptr,
    const std::vector<::flatbuffers::Offset<tensor::network::config::edge>> *edges = nullptr) {
  auto nodes__ = nodes ? _fbb.CreateVector<uint64_t>(*nodes) : 0;
  auto edges__ = edges ? _fbb.CreateVector<::flatbuffers::Offset<tensor::network::config::edge>>(*edges) : 0;
  return tensor::network::config::Creategraph(
      _fbb,
      nodes__,
      edges__);
}

struct network FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef networkBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_CONNECTIONS = 6
  };
  tensor::network::config::network_type type() const {
    return static_cast<tensor::network::config::network_type>(GetField<int16_t>(VT_TYPE, 0));
  }
  const tensor::network::config::graph *connections() const {
    return GetPointer<const tensor::network::config::graph *>(VT_CONNECTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_TYPE, 2) &&
           VerifyOffset(verifier, VT_CONNECTIONS) &&
           verifier.VerifyTable(connections()) &&
           verifier.EndTable();
  }
};

struct networkBuilder {
  typedef network Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(tensor::network::config::network_type type) {
    fbb_.AddElement<int16_t>(network::VT_TYPE, static_cast<int16_t>(type), 0);
  }
  void add_connections(::flatbuffers::Offset<tensor::network::config::graph> connections) {
    fbb_.AddOffset(network::VT_CONNECTIONS, connections);
  }
  explicit networkBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<network> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<network>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<network> Createnetwork(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    tensor::network::config::network_type type = tensor::network::config::network_type_link_based,
    ::flatbuffers::Offset<tensor::network::config::graph> connections = 0) {
  networkBuilder builder_(_fbb);
  builder_.add_connections(connections);
  builder_.add_type(type);
  return builder_.Finish();
}

inline const tensor::network::config::network *Getnetwork(const void *buf) {
  return ::flatbuffers::GetRoot<tensor::network::config::network>(buf);
}

inline const tensor::network::config::network *GetSizePrefixednetwork(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<tensor::network::config::network>(buf);
}

inline const char *networkIdentifier() {
  return "TNET";
}

inline bool networkBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, networkIdentifier());
}

inline bool SizePrefixednetworkBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, networkIdentifier(), true);
}

inline bool VerifynetworkBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<tensor::network::config::network>(networkIdentifier());
}

inline bool VerifySizePrefixednetworkBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<tensor::network::config::network>(networkIdentifier());
}

inline void FinishnetworkBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<tensor::network::config::network> root) {
  fbb.Finish(root, networkIdentifier());
}

inline void FinishSizePrefixednetworkBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<tensor::network::config::network> root) {
  fbb.FinishSizePrefixed(root, networkIdentifier());
}

}  // namespace config
}  // namespace network
}  // namespace tensor

#endif  // FLATBUFFERS_GENERATED_NETWORKSPEC_TENSOR_NETWORK_CONFIG_H_
