// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SIMULATIONLAYER_TENSOR_SIMULATION_H_
#define FLATBUFFERS_GENERATED_SIMULATIONLAYER_TENSOR_SIMULATION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace tensor {
namespace simulation {

struct layer;
struct layerBuilder;

enum layer_type : int16_t {
  layer_type_SIM_EVENT_LAYER = 0,
  layer_type_SIM_ANALYSIS_LAYER = 1,
  layer_type_SIM_COMM_LAYER = 2,
  layer_type_MIN = layer_type_SIM_EVENT_LAYER,
  layer_type_MAX = layer_type_SIM_COMM_LAYER
};

inline const layer_type (&EnumValueslayer_type())[3] {
  static const layer_type values[] = {
    layer_type_SIM_EVENT_LAYER,
    layer_type_SIM_ANALYSIS_LAYER,
    layer_type_SIM_COMM_LAYER
  };
  return values;
}

inline const char * const *EnumNameslayer_type() {
  static const char * const names[4] = {
    "SIM_EVENT_LAYER",
    "SIM_ANALYSIS_LAYER",
    "SIM_COMM_LAYER",
    nullptr
  };
  return names;
}

inline const char *EnumNamelayer_type(layer_type e) {
  if (::flatbuffers::IsOutRange(e, layer_type_SIM_EVENT_LAYER, layer_type_SIM_COMM_LAYER)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNameslayer_type()[index];
}

struct layer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef layerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_PATH = 6
  };
  tensor::simulation::layer_type type() const {
    return static_cast<tensor::simulation::layer_type>(GetField<int16_t>(VT_TYPE, 0));
  }
  const ::flatbuffers::String *path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_TYPE, 2) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(path()) &&
           verifier.EndTable();
  }
};

struct layerBuilder {
  typedef layer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(tensor::simulation::layer_type type) {
    fbb_.AddElement<int16_t>(layer::VT_TYPE, static_cast<int16_t>(type), 0);
  }
  void add_path(::flatbuffers::Offset<::flatbuffers::String> path) {
    fbb_.AddOffset(layer::VT_PATH, path);
  }
  explicit layerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<layer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<layer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<layer> Createlayer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    tensor::simulation::layer_type type = tensor::simulation::layer_type_SIM_EVENT_LAYER,
    ::flatbuffers::Offset<::flatbuffers::String> path = 0) {
  layerBuilder builder_(_fbb);
  builder_.add_path(path);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<layer> CreatelayerDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    tensor::simulation::layer_type type = tensor::simulation::layer_type_SIM_EVENT_LAYER,
    const char *path = nullptr) {
  auto path__ = path ? _fbb.CreateString(path) : 0;
  return tensor::simulation::Createlayer(
      _fbb,
      type,
      path__);
}

inline const tensor::simulation::layer *Getlayer(const void *buf) {
  return ::flatbuffers::GetRoot<tensor::simulation::layer>(buf);
}

inline const tensor::simulation::layer *GetSizePrefixedlayer(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<tensor::simulation::layer>(buf);
}

inline bool VerifylayerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<tensor::simulation::layer>(nullptr);
}

inline bool VerifySizePrefixedlayerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<tensor::simulation::layer>(nullptr);
}

inline void FinishlayerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<tensor::simulation::layer> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedlayerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<tensor::simulation::layer> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace simulation
}  // namespace tensor

#endif  // FLATBUFFERS_GENERATED_SIMULATIONLAYER_TENSOR_SIMULATION_H_
