// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SIMULATIONEVENT_TENSOR_SIMULATION_H_
#define FLATBUFFERS_GENERATED_SIMULATIONEVENT_TENSOR_SIMULATION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace tensor {
namespace simulation {

struct event;
struct eventBuilder;

enum event_type : int16_t {
  event_type_START_SIMULATION_EVENT = 0,
  event_type_STOP_SIMULATION_EVENT = 1,
  event_type_MIN = event_type_START_SIMULATION_EVENT,
  event_type_MAX = event_type_STOP_SIMULATION_EVENT
};

inline const event_type (&EnumValuesevent_type())[2] {
  static const event_type values[] = {
    event_type_START_SIMULATION_EVENT,
    event_type_STOP_SIMULATION_EVENT
  };
  return values;
}

inline const char * const *EnumNamesevent_type() {
  static const char * const names[3] = {
    "START_SIMULATION_EVENT",
    "STOP_SIMULATION_EVENT",
    nullptr
  };
  return names;
}

inline const char *EnumNameevent_type(event_type e) {
  if (::flatbuffers::IsOutRange(e, event_type_START_SIMULATION_EVENT, event_type_STOP_SIMULATION_EVENT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesevent_type()[index];
}

struct event FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef eventBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTEP = 4,
    VT_TYPE = 6
  };
  int16_t timestep() const {
    return GetField<int16_t>(VT_TIMESTEP, 0);
  }
  tensor::simulation::event_type type() const {
    return static_cast<tensor::simulation::event_type>(GetField<int16_t>(VT_TYPE, 0));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_TIMESTEP, 2) &&
           VerifyField<int16_t>(verifier, VT_TYPE, 2) &&
           verifier.EndTable();
  }
};

struct eventBuilder {
  typedef event Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestep(int16_t timestep) {
    fbb_.AddElement<int16_t>(event::VT_TIMESTEP, timestep, 0);
  }
  void add_type(tensor::simulation::event_type type) {
    fbb_.AddElement<int16_t>(event::VT_TYPE, static_cast<int16_t>(type), 0);
  }
  explicit eventBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<event> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<event>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<event> Createevent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t timestep = 0,
    tensor::simulation::event_type type = tensor::simulation::event_type_START_SIMULATION_EVENT) {
  eventBuilder builder_(_fbb);
  builder_.add_type(type);
  builder_.add_timestep(timestep);
  return builder_.Finish();
}

inline const tensor::simulation::event *Getevent(const void *buf) {
  return ::flatbuffers::GetRoot<tensor::simulation::event>(buf);
}

inline const tensor::simulation::event *GetSizePrefixedevent(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<tensor::simulation::event>(buf);
}

inline bool VerifyeventBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<tensor::simulation::event>(nullptr);
}

inline bool VerifySizePrefixedeventBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<tensor::simulation::event>(nullptr);
}

inline void FinisheventBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<tensor::simulation::event> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedeventBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<tensor::simulation::event> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace simulation
}  // namespace tensor

#endif  // FLATBUFFERS_GENERATED_SIMULATIONEVENT_TENSOR_SIMULATION_H_
