// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SIMULATIONCONFIG_TENSOR_SIMULATION_CONFIG_H_
#define FLATBUFFERS_GENERATED_SIMULATIONCONFIG_TENSOR_SIMULATION_CONFIG_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "binding_point_generated.h"
#include "network_spec_generated.h"
#include "simulation_event_generated.h"

namespace tensor {
namespace simulation {
namespace config {

struct layer_description;
struct layer_descriptionBuilder;

struct parameters;
struct parametersBuilder;

struct simulation;
struct simulationBuilder;

enum simulation_type : int16_t {
  simulation_type_link_network_simulation = 0,
  simulation_type_MIN = simulation_type_link_network_simulation,
  simulation_type_MAX = simulation_type_link_network_simulation
};

inline const simulation_type (&EnumValuessimulation_type())[1] {
  static const simulation_type values[] = {
    simulation_type_link_network_simulation
  };
  return values;
}

inline const char * const *EnumNamessimulation_type() {
  static const char * const names[2] = {
    "link_network_simulation",
    nullptr
  };
  return names;
}

inline const char *EnumNamesimulation_type(simulation_type e) {
  if (::flatbuffers::IsOutRange(e, simulation_type_link_network_simulation, simulation_type_link_network_simulation)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamessimulation_type()[index];
}

struct layer_description FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef layer_descriptionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PATH = 4,
    VT_NODES = 6
  };
  const ::flatbuffers::String *path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  const ::flatbuffers::Vector<uint64_t> *nodes() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_NODES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(path()) &&
           VerifyOffset(verifier, VT_NODES) &&
           verifier.VerifyVector(nodes()) &&
           verifier.EndTable();
  }
};

struct layer_descriptionBuilder {
  typedef layer_description Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_path(::flatbuffers::Offset<::flatbuffers::String> path) {
    fbb_.AddOffset(layer_description::VT_PATH, path);
  }
  void add_nodes(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> nodes) {
    fbb_.AddOffset(layer_description::VT_NODES, nodes);
  }
  explicit layer_descriptionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<layer_description> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<layer_description>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<layer_description> Createlayer_description(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> path = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> nodes = 0) {
  layer_descriptionBuilder builder_(_fbb);
  builder_.add_nodes(nodes);
  builder_.add_path(path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<layer_description> Createlayer_descriptionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *path = nullptr,
    const std::vector<uint64_t> *nodes = nullptr) {
  auto path__ = path ? _fbb.CreateString(path) : 0;
  auto nodes__ = nodes ? _fbb.CreateVector<uint64_t>(*nodes) : 0;
  return tensor::simulation::config::Createlayer_description(
      _fbb,
      path__,
      nodes__);
}

struct parameters FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef parametersBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INITIAL_NETWORK = 4,
    VT_MAIN_STEP_INTERVAL = 6
  };
  const tensor::network::config::network *initial_network() const {
    return GetPointer<const tensor::network::config::network *>(VT_INITIAL_NETWORK);
  }
  int16_t main_step_interval() const {
    return GetField<int16_t>(VT_MAIN_STEP_INTERVAL, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_INITIAL_NETWORK) &&
           verifier.VerifyTable(initial_network()) &&
           VerifyField<int16_t>(verifier, VT_MAIN_STEP_INTERVAL, 2) &&
           verifier.EndTable();
  }
};

struct parametersBuilder {
  typedef parameters Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_initial_network(::flatbuffers::Offset<tensor::network::config::network> initial_network) {
    fbb_.AddOffset(parameters::VT_INITIAL_NETWORK, initial_network);
  }
  void add_main_step_interval(int16_t main_step_interval) {
    fbb_.AddElement<int16_t>(parameters::VT_MAIN_STEP_INTERVAL, main_step_interval, 0);
  }
  explicit parametersBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<parameters> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<parameters>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<parameters> Createparameters(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<tensor::network::config::network> initial_network = 0,
    int16_t main_step_interval = 0) {
  parametersBuilder builder_(_fbb);
  builder_.add_initial_network(initial_network);
  builder_.add_main_step_interval(main_step_interval);
  return builder_.Finish();
}

struct simulation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef simulationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_DESCRIPTION = 6,
    VT_TYPE = 8,
    VT_SIM_PARAMS = 10,
    VT_EVENTS = 12,
    VT_LAYERS = 14,
    VT_CONTROL_BINDING_POINT = 16,
    VT_SHIM_ENDPOINT = 18,
    VT_COMM_ENDPOINT = 20
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  tensor::simulation::config::simulation_type type() const {
    return static_cast<tensor::simulation::config::simulation_type>(GetField<int16_t>(VT_TYPE, 0));
  }
  const tensor::simulation::config::parameters *sim_params() const {
    return GetPointer<const tensor::simulation::config::parameters *>(VT_SIM_PARAMS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<tensor::simulation::event>> *events() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<tensor::simulation::event>> *>(VT_EVENTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<tensor::simulation::config::layer_description>> *layers() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<tensor::simulation::config::layer_description>> *>(VT_LAYERS);
  }
  const tensor::simulation::binding_point *control_binding_point() const {
    return GetPointer<const tensor::simulation::binding_point *>(VT_CONTROL_BINDING_POINT);
  }
  const tensor::simulation::binding_point *shim_endpoint() const {
    return GetPointer<const tensor::simulation::binding_point *>(VT_SHIM_ENDPOINT);
  }
  const tensor::simulation::binding_point *comm_endpoint() const {
    return GetPointer<const tensor::simulation::binding_point *>(VT_COMM_ENDPOINT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyField<int16_t>(verifier, VT_TYPE, 2) &&
           VerifyOffset(verifier, VT_SIM_PARAMS) &&
           verifier.VerifyTable(sim_params()) &&
           VerifyOffset(verifier, VT_EVENTS) &&
           verifier.VerifyVector(events()) &&
           verifier.VerifyVectorOfTables(events()) &&
           VerifyOffset(verifier, VT_LAYERS) &&
           verifier.VerifyVector(layers()) &&
           verifier.VerifyVectorOfTables(layers()) &&
           VerifyOffset(verifier, VT_CONTROL_BINDING_POINT) &&
           verifier.VerifyTable(control_binding_point()) &&
           VerifyOffset(verifier, VT_SHIM_ENDPOINT) &&
           verifier.VerifyTable(shim_endpoint()) &&
           VerifyOffset(verifier, VT_COMM_ENDPOINT) &&
           verifier.VerifyTable(comm_endpoint()) &&
           verifier.EndTable();
  }
};

struct simulationBuilder {
  typedef simulation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(simulation::VT_NAME, name);
  }
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(simulation::VT_DESCRIPTION, description);
  }
  void add_type(tensor::simulation::config::simulation_type type) {
    fbb_.AddElement<int16_t>(simulation::VT_TYPE, static_cast<int16_t>(type), 0);
  }
  void add_sim_params(::flatbuffers::Offset<tensor::simulation::config::parameters> sim_params) {
    fbb_.AddOffset(simulation::VT_SIM_PARAMS, sim_params);
  }
  void add_events(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<tensor::simulation::event>>> events) {
    fbb_.AddOffset(simulation::VT_EVENTS, events);
  }
  void add_layers(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<tensor::simulation::config::layer_description>>> layers) {
    fbb_.AddOffset(simulation::VT_LAYERS, layers);
  }
  void add_control_binding_point(::flatbuffers::Offset<tensor::simulation::binding_point> control_binding_point) {
    fbb_.AddOffset(simulation::VT_CONTROL_BINDING_POINT, control_binding_point);
  }
  void add_shim_endpoint(::flatbuffers::Offset<tensor::simulation::binding_point> shim_endpoint) {
    fbb_.AddOffset(simulation::VT_SHIM_ENDPOINT, shim_endpoint);
  }
  void add_comm_endpoint(::flatbuffers::Offset<tensor::simulation::binding_point> comm_endpoint) {
    fbb_.AddOffset(simulation::VT_COMM_ENDPOINT, comm_endpoint);
  }
  explicit simulationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<simulation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<simulation>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<simulation> Createsimulation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0,
    tensor::simulation::config::simulation_type type = tensor::simulation::config::simulation_type_link_network_simulation,
    ::flatbuffers::Offset<tensor::simulation::config::parameters> sim_params = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<tensor::simulation::event>>> events = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<tensor::simulation::config::layer_description>>> layers = 0,
    ::flatbuffers::Offset<tensor::simulation::binding_point> control_binding_point = 0,
    ::flatbuffers::Offset<tensor::simulation::binding_point> shim_endpoint = 0,
    ::flatbuffers::Offset<tensor::simulation::binding_point> comm_endpoint = 0) {
  simulationBuilder builder_(_fbb);
  builder_.add_comm_endpoint(comm_endpoint);
  builder_.add_shim_endpoint(shim_endpoint);
  builder_.add_control_binding_point(control_binding_point);
  builder_.add_layers(layers);
  builder_.add_events(events);
  builder_.add_sim_params(sim_params);
  builder_.add_description(description);
  builder_.add_name(name);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<simulation> CreatesimulationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *description = nullptr,
    tensor::simulation::config::simulation_type type = tensor::simulation::config::simulation_type_link_network_simulation,
    ::flatbuffers::Offset<tensor::simulation::config::parameters> sim_params = 0,
    const std::vector<::flatbuffers::Offset<tensor::simulation::event>> *events = nullptr,
    const std::vector<::flatbuffers::Offset<tensor::simulation::config::layer_description>> *layers = nullptr,
    ::flatbuffers::Offset<tensor::simulation::binding_point> control_binding_point = 0,
    ::flatbuffers::Offset<tensor::simulation::binding_point> shim_endpoint = 0,
    ::flatbuffers::Offset<tensor::simulation::binding_point> comm_endpoint = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto description__ = description ? _fbb.CreateString(description) : 0;
  auto events__ = events ? _fbb.CreateVector<::flatbuffers::Offset<tensor::simulation::event>>(*events) : 0;
  auto layers__ = layers ? _fbb.CreateVector<::flatbuffers::Offset<tensor::simulation::config::layer_description>>(*layers) : 0;
  return tensor::simulation::config::Createsimulation(
      _fbb,
      name__,
      description__,
      type,
      sim_params,
      events__,
      layers__,
      control_binding_point,
      shim_endpoint,
      comm_endpoint);
}

inline const tensor::simulation::config::simulation *Getsimulation(const void *buf) {
  return ::flatbuffers::GetRoot<tensor::simulation::config::simulation>(buf);
}

inline const tensor::simulation::config::simulation *GetSizePrefixedsimulation(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<tensor::simulation::config::simulation>(buf);
}

inline const char *simulationIdentifier() {
  return "tsim";
}

inline bool simulationBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, simulationIdentifier());
}

inline bool SizePrefixedsimulationBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, simulationIdentifier(), true);
}

inline bool VerifysimulationBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<tensor::simulation::config::simulation>(simulationIdentifier());
}

inline bool VerifySizePrefixedsimulationBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<tensor::simulation::config::simulation>(simulationIdentifier());
}

inline const char *simulationExtension() {
  return "tsim";
}

inline void FinishsimulationBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<tensor::simulation::config::simulation> root) {
  fbb.Finish(root, simulationIdentifier());
}

inline void FinishSizePrefixedsimulationBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<tensor::simulation::config::simulation> root) {
  fbb.FinishSizePrefixed(root, simulationIdentifier());
}

}  // namespace config
}  // namespace simulation
}  // namespace tensor

#endif  // FLATBUFFERS_GENERATED_SIMULATIONCONFIG_TENSOR_SIMULATION_CONFIG_H_
